=== aj-carmona/xml-ubuntu/xslt/catalogo.dtd
<!ELEMENT animes (anime+)>
<!ELEMENT anime (titulo, estudio, genero, ano)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT estudio (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT ano (#PCDATA)>

=== aj-carmona/xml-ubuntu/xslt/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animes SYSTEM "catalogo.dtd">

<animes>
    <anime>
        <titulo>One Piece</titulo>
        <estudio>Wit Studio</estudio>
        <genero>Accion</genero>
        <ano>1999</ano>
    </anime>
        
    <anime>
        <titulo>Shingeki no Kyojin</titulo>
        <estudio>Wit Studio</estudio>
        <genero>Fantasia oscura</genero>
        <ano>2011</ano>
    </anime>

    <anime>
        <titulo>Naruto</titulo>
        <estudio>Artes Marciales</estudio>
        <genero>Pierrot</genero>
        <ano>1979</ano>
    </anime>
</animes>
