=== aj-carmona/xml-ubuntu/xslt/gimnasio.dtd
<!ELEMENT gimnasio (miembro+)>
<!ELEMENT miembro (nombre, listaclases)>
<!ATTLIST miembro id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT listaclases (clases+)>
<!ELEMENT clases (#PCDATA)>

=== aj-carmona/xml-ubuntu/xslt/gimnasio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gimnasio SYSTEM "gimnasio.dtd">

<gimnasio>
    <miembro id="1">
        <nombre>Manolo</nombre>
        <listaclases>
            <clases>Yoga</clases>
            <clases>Spining</clases>
            <clases>Body Combat</clases>
        </listaclases>
    </miembro>
    <miembro id="2">
        <nombre>Paco</nombre>
        <listaclases>
            <clases>Zumba</clases>
            <clases>Aerobic</clases>
            <clases>Yoga</clases>
        </listaclases>
    </miembro>
    <miembro id="3">
        <nombre>Maria</nombre>
        <listaclases>
            <clases>Body Combat</clases>
            <clases>Spining</clases>
            <clases>Zumbac</clases>
        </listaclases>
    </miembro>
</gimnasio>
